### ISSUE TITLE
HTTP Status 404 - Not Found

### ISSUE THREAD

**Issue by kennethabuelxd** [ghaseminya/ketabhome#1]
/servlet/LoginServlet

Cloned it and put the .war file on tomcat, what's problem?

**Comment by ghaseminya** [comment]
Hi @kennethabuelxd 
Are you import sql on your mysql?
Are you set database config in your clone?

**Comment by kennethabuelxd** [comment]
Yes, I did import the sql file. By the way what do you mean set database config?
